API_BASE = "http://localhost:5000"

LOGIN_EMAIL = "manager@pos.com"
LOGIN_PASSWORD = "changeme"

STORE_ID = 1

SHIFT_START_HOUR = 9
SHIFT_START_MINUTE = 0
GRACE_MINUTES = 15

MATCH_THRESHOLD = 0.40
MARK_COOLDOWN_SECONDS = 300
CAMERA_INDEX = 0